apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app
spec:
  secretName: app
  issuerRef:
    name: production-app
    kind: ClusterIssuer
  commonName: demo.ksiddhiapphub.org
  dnsNames:
  - demo.ksiddhiapphub.org